name: CI

on: [pull_request, push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install Python Dependencies
      run: |
        pip install -r source/requirements.txt
    - name: Install librsvg2
      run: |
        sudo apt-fast -y update
        sudo apt-fast install -y librsvg2-bin
    - name: Build HTML
      run: |
        make html
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/html/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
